runtime: python39  # Adjust the Python version to match your application's requirements.

entrypoint: gunicorn -b :$PORT nhs_document_api:app  # Adjusted to point to your application file.

env_variables:
  # Define any necessary environment variables here.
  # For example:
  # DATABASE_URL: "your-database-url"

# Ensure you have a 'requirements.txt' file in the same directory as your 'app.yaml'.
# This file should list all your Python dependencies, like 'Flask', 'gunicorn', 'pysqlite3', etc.
